name: application
description: "GOSTGuard Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_svg: ^2.0.10

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2  # Добавляем для Windows поддержки
  path: ^1.8.3
  path_provider: ^2.1.3  # Для работы с путями файлов

  # File Operations
  open_file: ^3.3.3  # Для открытия файлов
  share_plus: ^12.0.1  # Для шеринга файлов

  # HTTP
  http: ^1.1.0

  # Utils
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - image/

